importer-guidelines.md
About to try the importer for the first time and was reading over the guidelines. Saw some issues so I hope you don't mind the changes ;)
Some words used the British spelling, changed those to use the American version as I'm assuming that is preferred.
Add some other small grammar updates.
=> chore: fix guideline typos

crawl.html, js/crawl/crawl.ui.js
Some sites are sub-sites on a given host. It might be interesting to only crawl a given sub-site and not go through the full host.
Note that there is a difference between the 2 actions:
- `Get from robots.txt or sitemap` processes all sitemaps and then filter the urls
- ` Crawl` only crawl the next page if the filter matches. A page only accessible from the parent host would not be found.
=> feat: allow to filter the crawling

import-bulk.html, import.html, js/import/import.ui.js
Scroll to bottom in the preview frame. This can be useful if images are loaded eager or even via Javascript. The scroll happens before the page load timeout which allows to tweak the time to wait before executing the import script (give time to images to be downloaded).
=> feat: scroll to bottom

js/shared/sitemap.js
Try to crawl urls from sitemap on site: https://www.eder-gmbh.de/
This crashes the browser.
Root cause: infinite loop.
Explanation: sitemap.xml file contains 2 references:
- https://www.eder-gmbh.de/sitemap.xml?sitemap=pages&amp;cHash=219806291a8377c2a5347573b5d50f24
- https://www.eder-gmbh.de/sitemap.xml?sitemap=news&amp;cHash=d8277f1d000b07961fe1367319dbb1b4
The query parameters are ignored thus infinite loop...
=> fix: do not ignore query parameters

importer-guidelines.md, js/import/import.ui.js, package.json
Using the `transform` method and add an extra `report` object:
{
path: String,
element: DOMElement,
report: Object
}
Each top level property of the `report` object will be considered as a report column.
=> feat: add extra report columns

importer-guidelines.md, package-lock.json, package.json
By using the reporting capability and omitting the `element` property of the `transform` returned object, you can skip the `docx` files creation and only feed the report `xlsx` with data.
=> feat: document how to collect site data without creating docx files

modules/importer.js
We were struggling with 2 issues:
- if the image width or height is not a round number, the docx is corrupted.
- if svg image contains a png, `image2png` fails and the docx is corrupted. I did not find an elegant way to fix this apart from informing the dev that the image might need to be removed.
=> fix: round image w/h and improve logging

js/import/import.ui.js
Simpler implementation than what we discussed yesterday but it's also a simpler one. The idea is to re-use the "Page Load Timeout".
1. (if enabled) Scroll right after page load to trigger potential lazy loading
2. (if enabled) wait "Page Load Timeout" time
3. (if enabled) Scroll once more in case lazy loading took some time to finish
1. scroll to bottom
2. wait 250ms
3. check if main scrollHeight increase:
1. If yes => 1.
2. If no => stop!
* URL: https://www.adobe.com/products/substance3d-modeler.html
* min "Page Load Timeout": 1s.
* Enable "Scroll to bottom"
Decrease "Page Load Timeout" to check that lazy loading is not imported.
=> Refactor scroll flow to better handle lazy loading

js/import/import.ui.js
For long imports (1000+ pages), it is required to know the total elapsed time to evaluate the next run durations.
=> feat: display total elapsed time

css/import/import.css
I find this improvement even more meaningful since addition of elapsed time.
Screenshot:
=> Make import result header stick to top when scrolling list

crawl.html, import-bulk.html, import.html, inspect.html, js/shared/log.js
Some imported pages flood the console with lots of errors, warnings or even logs. It is hard to extract the info from the importer. By prepending all console.log with a marker (chosen one so far `[importer-ui]`), we can filter out all the rest and views what is going on during the import process.
=> feat: prepend [importer-ui] to be able to filter logs

js/import/import.ui.js
Unexpected fetch error may occur (like in the CORS case) - this breaks the import process while it should be caught and treated as an error.
=> feat: catch error and give hint

README.md, import-bulk.html, import.html, js/import/import.ui.js
Having the capability to provide custom headers to the request made to fetch the remote server content might be required: for certain JSON API request, we need to pass an header token.
=> feat: add optional custom headers field

js/import/import.ui.js
#150 introduced an issue: the content frame now loaded via the remote url, which means the proxy is by-passed, thus re-introducing CSP issues.
=> fix: use proxied url as content base

importer-guidelines.md, js/shared/pollimporter.js
Fix #183
2 options to fix the issue:
- revert the `document.cloneNode(true)` and use the original. This would require the enduser to click on import each time they want to get a fresh document to work on
- copy the styles we need - since `document.cloneNode(true)` does not copy the style, we need to inline them in the clone
With this PR, we need to traverse the document to copy and inline the style properties defined as required. By default, only `background-image` is defined. But the list could be controlled in `import.js` via:
```js
export default {
transformDOM() {...},
REQUIRED_STYLES: ['background-image', /* add more here if needed */],
```
=> fix: clone and copy styles

js/crawl/crawl.ui.js
Fixes #190 
What it does:
1. Add common extensions to the exclusion list
2. Denies automated download in the crawl iframe to trigger standard warning notification in web console to help inform the user about an unsupported extension that is breaking the crawling flow.
3. Add reporting about excluded URLs
About 2., I could not catch the "download" event in the iframe so I cannot generate an alert ribbon in the application UI so the only notification is the standard one in the web console.
=> [crawl] Fix non html URLs

README.md
Proposal to fix #187.
Feedback welcome on the wording! :)
I'm wondering if we should double that information on the import-guidelines. On one hand it would not hurt but on the other hand it's more an information about the UI configuration/convention.
@kptdobe, any thoughts?
=> docs: clarify location of the import script

js/crawl/crawl.ui.js, js/shared/sitemap.js
fixes #193.
* auto fix space issue on sitemap content (https://github.com/adobe/helix-importer-ui/commit/ea4b8b9daaaa9bce80498fd3fd0a596ea65677d2)
* catch sitemap parsing issues and notify user via alert banner in the UI (https://github.com/adobe/helix-importer-ui/commit/7f0f333a7d8f7ccc127c4b705b8fd10be084aa62)
The fix should be tested on https://www.sunstar-foundation.org/ (as their sitemap https://www.sunstar-foundation.org/sitemap.xml has syntax errors) but this PR includes a small trick to auto fix extra space issues ( commit https://github.com/adobe/helix-importer-ui/commit/ea4b8b9daaaa9bce80498fd3fd0a596ea65677d2).
So in order to test the fix, if you don't have any URL of wrong sitemap, remove the `.trim()` and test on https://www.sunstar-foundation.org/
=> fix: crawl silently failing on sitemap parsing errors

js/shared/sitemap.js
Try to crawl from `robots.txt / sitemap` the site: https://www.xeljanz.com/
It finds `robots.txt` and it does to contain a sitemap reference... Ideally, the code falls back to still try `sitemap.xml` (or the one defined in the config).
=> feat: use default sitemap if no sitemap found in robots.txt

importer-guidelines.md
While debugging, it might be valuable at times to make updates to `helix-importer` dependency's code to fix certain behaviours (and propose PRs).
Adding additional instructions for how to set that up
=> Additional instructions for setting up `helix-importer` for fixes

css/styles.css
Removed an unnecessary margin-left that was causing the import options to be cut off 
Fix: #249 
Fixes a bad user experience that is annoying to see and use.
run `hlx up` locally to test the fix
**Before:**
**After:**
=> margin fix

css/inspect/inspect.css, inspect.html, js/inspect/inspect.ui.js
Fix #278 and #279 
- add JS execution warning (same as for import uis)
- show icon svg as a background image (no JS execution in that case)
- if icon svg, add a security risk warning `Security risk: the logo you have selected is an SVG. It may contain malicious code (like Javascript code). You can download it but you should inspect it before using it.`
=> Eyedropper security

js/import/import.ui.js
The current behaviour is causing issues when not all reports n a bulk import contain the same fields, meaning that if we have a report with fields a, b, c, and another one with b,c, in the resulting excel sheet the first report will appear correctly, and the second while have b assigned to a, and c assigned to be.
Fix #283
I'm trying to generate a report that will be used to generate an excel sheet so that it can be queried on the site. This is needed for the excel to be generated correctly.
Tested manually in the revolt tv project (access to the code is limited to contributors, but can share more if need be).
=> #283 Ensure report extra columns are assigned to the correct column in excel

js/inspect/inspect.js
Fixes https://github.com/adobe/helix-importer-ui/issues/281
When given page does not have content at its center, eyedropper cannot find any DOM element to which adding dummy visual elements (`HX`, `a`, ...).
The fix adds a fallback to document.body when center is null. 
https://github.com/adobe/helix-importer-ui/issues/281
Tested on a local test project
=> fix: handle pages with no content at their center

package.json
I noticed the package name in `package.json` is not aligned with the repository
name, so I fixed it. I also added the `@adobe` prefix, should we ever need to
release this to NPM
=> build(package): fix package name

.github/workflows/main.yaml
Enable branch protection and use adobe-bot for releases.
=> chore: use adobe-bot token

.gitignore, js/crawl/crawl.ui.js
Also evaluate a possible page path with the provided filter as a RegExp (not just startsWith).
Ensure current behavior is not changed.
#381 (Hubble Homes VIP)
Hubble Homes has a very distinct path for a certain template.  The path ends in "/999".  They'd like to target the import to only work on those pages.
Manually.
Nothing changed visually.
=> [Feat] #381 Also consider crawl filter as a regexp

js/import/import.ui.js, js/script.js, js/sections-mapping/import/parsers/header.js, js/sections-mapping/import/sections-mapping.import.js, js/sections-mapping/sm.ui.js
PR Contains:
* feat: new dedicated parser for header navigation
* feat: when adding a new section, auto assign Columns/Header parsers
* feat: when in demo tool context, auto select the "Import - Fragments" UI
* feat: add metadata block when not in crosswalk target
* fix: improve section mapping data saving
* fix: ui glitch where section was not getting selected when clicking on it
* fix: minor ui fixes
=> [SM Import] Changes coming from Feedback 01

importer-guidelines.md
[doc] Hot reload imported files
Issue #267
Use `esbuild` to bundle the import javascript files which allows the UI to hot load all changed files.
https://github.com/adobe/helix-importer-ui/issues/267
Instructions followed locally, and each change of the dependency caused a reload (i.e. the console had the entry `[importer-ui] Loaded importer file: http://localhost:3001/tools/importer/import.js?cf=1724101118347` appear each time)
=> [doc] Hot reload imported files

css/import/import.css, import-bulk.html, import.html, js/import/import.ui.js, js/shared/pollimporter.js
A non-existent transformation file is allows, as the default one will then be used, but if a non-existent one is used by accident, it causes confusion for the user, since they think their import script is broken.
If the default transformation file is being used, give the user a subtle note about it is happening.
#258 
Small note to avoid confusion.
Tested locally, doing imports with the existing files, non-existing files and plain old strangely spelled files.
@kptdobe  For your consideration...
=> 258 Indicate if default transformation file is being used
