adobe/helix-importer-ui

- js/import/import.ui.js
- modules/importer.js
- package-lock.json
- package.json
> feat: download pdfs during bulk import

- js/crawl/crawl.ui.js
Extra are missing in crawling report
> fix: add missing extra

- importer-guidelines.md
Add special note about `blockquote`
https://github.com/adobe/helix-importer/issues/29
Improved documentation
> chore: Add special note about `blockquote`

- CONTRIBUTING.md
- README.md
- importer-guidelines.md
- index.html
- inspect.html
> feat: rename

- modules/md2html.js
- package-lock.json
- package.json
Update dependency and fix the build.
> feat: update to latest helix-importer

- .github/workflows/branch.yaml
- .stylelintignore
- css/import/import.css
- css/styles.css
- package-lock.json
- webpack.common.cjs
Tests are not executed in branches which lead the release to fail recently.
> fix: add tests and repair release

- css/styles.css
- js/script.js
> feat: show project name and version

- importer-guidelines.md
- js/import/import.ui.js
Adds support for Excel formulas. See corresponding documentation.
> feat: support for Excel formulas

- css/import/import.css
- js/import/import.ui.js
- modules/swc.js
Fixes the count which does not update for erroneous entries
Add status icons for each entry
> feat: enhance bulk UI

- js/import/import.ui.js
If the browser crashes during a long bulk import, it is frustrating to lose the report which a status where it was...)
> feat: auto save report in directory in bulk mode

- docs/download-pdf.md
- import-bulk.html
- import.html
- importer-guidelines.md
- js/import/import.ui.js
- package.json
Adds the capability to download pdfs - or any other type of resource that can be downloaded.
> feat: support for pdf download

- importer-guidelines.md
Depends on #102 
Adds corresponding documentation (+ document the `preprocess` function)
> chore: document advanced usages

- js/import/import.ui.js
Quality of Life: improve HTML preview
From
```
<main>
<table>
<tr>
<th colspan="2">marquee (small, light)</th>
</tr>
<tr>
<td colspan="2">#f5f5f5</td>
</tr>
<tr>
<td>
<h6>REPORT</h6>
<h1>The heart of IT transformation for</h1>
</td>
<td></td>
</tr>
</table>---<table>
<tr>
<th colspan="2">Columns (contained)</th>
</tr>
<tr>
<td>
<div class="flex_2016368841 flex aem-GridColumn aem-GridColumn--default--12">
<div id="root_flex_2016368841" class="dexter-FlexContainer  
">
<div class="dexter-FlexContainer-Items   dexter-FlexContainer--mobileJustifyCenter dexter-FlexContainer--mobileAlignItemCenter dexter-FlexContainer--mobileAlignContentCenter dexter-FlexContainer--mobileAlignItemContentCenter">
<div class="flex">
<div id="root_flex_2016368841_items_flex_copy_1663389260" …
```
> feat: QoL - Remove empty lines in html preview

- js/import/import.ui.js
> fix: show preview tab on first import

- js/import/import.ui.js
> fix: import gives correct feedback

- crawl.html
- import-bulk.html
- import.html
> feat: disable JS execution by default and add warning

- js/crawl/crawl.ui.js
- js/import/import.ui.js
- js/inspect/inspect.js
- js/script.js
- js/shared/alert.js
> feat: review innerHTML usages

- js/import/import.ui.js
> fix: load non json resources without blob

- js/import/import.ui.js
> feat: report importer errors

- css/styles.css
- js/crawl/crawl.ui.js
- js/import/import.ui.js
- js/inspect/inspect.ui.js
- js/shared/ui.js
- modules/swc.js
Add a loading spinners to inform something is going on.
> feat: add loading spinners to all long-running tasks buttons

- js/import/import.ui.js
- js/shared/alert.js
Minor ui improvements for 301:
- toast indicating page is a redirect
- console log with original url and target host redirect location
- better xlsx columns default sizing
> feat: better enduser feedback for redirects

- js/import/import.ui.js
Fix #329
- add a try/catch to not crash the rest of the import post processing sequence
- display a "No preview available" message instead of crashing - #328 would be the follow-up task.
> fix: support no preview available case

- js/import/import.ui.js
Exporting the mappings data saved in localstorage as sections-mapping.json. This would be used to capture screenshots of the selected sections & leveraging AI to decorate the blocks as close as the original site.
> AEM Assistant: Export mappings data for refining the generated blocks using AI

- js/import/import.ui.js
> fix: Locally save sections-mapping.json when importer-ui is executed by demo-tool

- js/sections-mapping/import/parsers/cards.js
- js/sections-mapping/import/parsers/carousel.js
- js/sections-mapping/import/parsers/columns.js
- js/sections-mapping/import/parsers/hero.js
- js/sections-mapping/sm.ui.js
In order to support cases where multiple blocks of same type are there (e.g. cards) but the styling is different on the various usages. This addition of variant would help aem-assistant to distinguish between different cards block.
https://github.com/adobe/helix-importer-ui/assets/25667166/e9c27638-2f45-4fd8-bcb1-4f39d5e64964
> feat: Added variant field for the block selected in a section

- js/sections-mapping/import/parsers/header.js
* Better extract navigation content
* Handle brand logo image with link
* Put hidden content inside a `hidden` section (`section-metadata` block)
> Fix (sm-import): Improve header parser

- css/import/import.css
- css/styles.css
- import-bulk.html
- import.html
- js/import/import.bulk.js
- js/import/import.result.js
- js/import/import.ui.js
- js/shared/jcr/field-listener.js
- js/shared/jcr/imageurl.mapping.js
- js/shared/jcr/packaging.js
- js/shared/pollimporter.js
- js/shared/project.js
- package-lock.json
- package.json
* Support JCR imports for bulk operations.  
* Adjust Bulk UI to have it be more manageable with large lists. 
* Auto detect project type, xwalk or doc based
* Always generate the jcr xml for xwalk based, and generate a package when requested
> fix: support bulk for md2jcr

- js/import/import.ui.js
> fix(495): unable to import a url that ends in /

- modules/importer.js
> fix: image2png function must await to get buffer data from the blob

- js/shared/document.js
> fix: custom headers are not being set

- js/shared/pollimporter.js
> fix: jcr - html comments are lost when an error is thrown
